### ISSUE TITLE
这个uboot能启动你仓库padavan4.4 里面jdcloud-re-cp-02固件吗？我刷了你的uboot，请问怎么刷其他的uboot，ttl没有选项啊！也刷了其他固件都无法启动固件，求救！主要是spi为XM25QH128C

### ISSUE THREAD

**Issue by monw** [lyq1996/MT7621-U-Boot#1]

**Comment by lyq1996** [comment]
机型是re-cp-02吗？  这个uboot可以启动openwrt和官方固件，padavan没试

**Comment by lyq1996** [comment]
用re-cp-02的defconfig编译，xmc flash配置已开。

另外编译的时候如果没选xmc flash的支持也不要慌，用tftp下载固件到内存里，直接从内存指定地址启动，进系统后再mtd重刷uboot。

**Comment by monw** [comment]
我的不是re-cp-02机型，是类似的，没有emmc而已。刷过后，不能启动固件，官方的固件和openwrt都不行，后面自己编译了一个uboot，使用的sdk编译的，添加了spi信息。从你的1.0 uboot没法用tftp加载，选项被你剔除了，只有一个刷机界面。
